### ISSUE TITLE
 Cannot query field "allStripeSku" on type "Query"

### ISSUE THREAD

**Issue by sobowalebukola** [thorsten-stripe/ecommerce-gatsby-tutorial#2]
<img width="975" alt="screen shot 2019-01-16 at 8 32 16 pm" src="https://user-images.githubusercontent.com/29496092/51273801-df7cd100-19cd-11e9-8e95-c072e19d8c0a.png">

**Comment by DavidSabine** [comment]
Hi @sobowalebukola,

I've been successful with this tutorial, and I've implemented this beta version of stripe checkout in my own Gatsby project.

I've encountered the error you posted WHEN I did not have the appropriate Stripe secret key, or when the secret key was not available to Gastby.

I can reproduce your error exactly by:
- removing my secret from my environment variables;
- or by messing with this code in `gatsby-config.js`

```JavaScript
		{
			resolve: `gatsby-source-stripe`,
			options: {
				objects: [`Sku`],
				secretKey: process.env.STRIPE_SECRET_KEY,
				downloadFiles: true,
			}
		},
```

**Comment by sobowalebukola** [comment]
Thanks🙏🏾

**Comment by develo-pera** [comment]
I have the same issue but I don't think it's because of the wrong Stripe secret key. I've even hardcoded it and it still doesn't work, I rolled the secret key and tried with the new one and I have the same problem.

Gatsby CLI version: 2.8.11
Gatsby version: 2.17.11
Node version: 10.16.0

**Comment by woudsma** [comment]
I had the same problem.
Fixed it by creating a test product in Stripe (under Orders > Products).
Make sure to fill in a product name and description, etc.
Also make sure to create a `.env.development` file containing:
```
GATSBY_STRIPE_PUBLISHABLE_KEY=<your stripe public key>
STRIPE_SECRET_KEY=<your stripe secret key>
```
Then run `gatsby develop` again.
